### PR TITLE
Center all text in about screen

### PR DESCRIPTION
**Pull request by sandakersmann**
Think this will give a more clean look to the about screen.

### CODE REVIEW

**Comment by willyfromtheblock** [comment]
grafik
removing the line breaks looks very weird on web

**Comment by sandakersmann** [comment]
Looks fine to me

**Comment by willyfromtheblock** [comment]
I disagree. The line breaks are there on purpose to highlight certain thinks for better readability. We're limited in width on all devices, but never in height. 

This will also flag all those items to be re translated on the weblate.

**Comment by sandakersmann** [comment]
Agree to disagree then I guess.

**Pull request closed without merging**
