### PR TITLE
Add traditional Chinese

### PR DESCRIPTION
**Pull request by sandakersmann**
Add traditional Chinese

### CODE REVIEW

**Comment by willyfromtheblock** [comment]
please check https://api.flutter.dev/flutter/flutter_localizations/kMaterialSupportedLanguages.html

**Comment by sandakersmann** [comment]
ChatGPT:
Screenshot from 2023-07-26 13-28-10

**Comment by sandakersmann** [comment]
@willyfromtheblock I'm not a Flutter man, so I hope you can figure it out :)

**Comment by willyfromtheblock** [comment]
https://github.com/peercoin/peercoin_flutter/commit/1e126e939f45393dc71d73a66ddb4ed25197aa46

Will allow you do to accomplish what you're trying :)

**Comment by sandakersmann** [comment]
@willyfromtheblock Do you think this will work?

**Pull request closed without merging**
